# Generated by Django 2.2.5 on 2020-12-10 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20201210_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='subtitle',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
